2024-08-07 11:07:35,544 - INFO - Configuración cargada desde c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\config.txt.
2024-08-07 11:07:41,949 - INFO - Ruta de la base de datos seleccionada: C:/Users/Windows/Desktop/CSV/9992024.accdb
2024-08-07 11:07:45,027 - INFO - Carpeta de salida CSV seleccionada: C:/Users/Windows/Desktop/CSV
2024-08-07 11:07:46,666 - INFO - Iniciando sincronización manual...
2024-08-07 11:07:46,668 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py C:/Users/Windows/Desktop/CSV/9992024.accdb C:/Users/Windows/Desktop/CSV
2024-08-07 11:07:49,680 - INFO - STDOUT: Datos exportados de la tabla F_ART a C:/Users/Windows/Desktop/CSV\F_ART.csv
Datos exportados de la tabla F_ARC a C:/Users/Windows/Desktop/CSV\F_ARC.csv
Datos exportados de la tabla F_STO a C:/Users/Windows/Desktop/CSV\F_STO.csv
Datos exportados de la tabla F_STC a C:/Users/Windows/Desktop/CSV\F_STC.csv
Datos exportados de la tabla F_LTA a C:/Users/Windows/Desktop/CSV\F_LTA.csv
Datos exportados de la tabla F_LTC a C:/Users/Windows/Desktop/CSV\F_LTC.csv
Datos exportados de la tabla F_ALM a C:/Users/Windows/Desktop/CSV\F_ALM.csv
Datos exportados de la tabla F_TAR a C:/Users/Windows/Desktop/CSV\F_TAR.csv
Datos exportados de la tabla F_FAM a C:/Users/Windows/Desktop/CSV\F_FAM.csv
Datos exportados de la tabla F_SEC a C:/Users/Windows/Desktop/CSV\F_SEC.csv

2024-08-07 11:07:49,684 - INFO - STDERR: c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

2024-08-07 11:07:49,688 - INFO - Exportación a CSV completada con éxito.
2024-08-07 11:07:49,690 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\conversor_json.py C:/Users/Windows/Desktop/CSV\F_ART.csv C:/Users/Windows/Desktop/CSV\F_LTA.csv C:/Users/Windows/Desktop/CSV\F_STO.csv
2024-08-07 11:31:46,375 - INFO - Configuración cargada desde c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\config.txt.
2024-08-07 11:31:49,606 - INFO - Ruta de la base de datos seleccionada: C:/Users/Windows/Desktop/CSV/9992024.accdb
2024-08-07 11:31:51,839 - INFO - Carpeta de salida CSV seleccionada: C:/Users/Windows/Desktop/CSV
2024-08-07 11:32:04,437 - INFO - Iniciando sincronización manual...
2024-08-07 11:32:04,438 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py C:/Users/Windows/Desktop/CSV/9992024.accdb C:/Users/Windows/Desktop/CSV
2024-08-07 11:32:07,451 - INFO - STDOUT: Datos exportados de la tabla F_ART a C:/Users/Windows/Desktop/CSV\F_ART.csv
Datos exportados de la tabla F_ARC a C:/Users/Windows/Desktop/CSV\F_ARC.csv
Datos exportados de la tabla F_STO a C:/Users/Windows/Desktop/CSV\F_STO.csv
Datos exportados de la tabla F_STC a C:/Users/Windows/Desktop/CSV\F_STC.csv
Datos exportados de la tabla F_LTA a C:/Users/Windows/Desktop/CSV\F_LTA.csv
Datos exportados de la tabla F_LTC a C:/Users/Windows/Desktop/CSV\F_LTC.csv
Datos exportados de la tabla F_ALM a C:/Users/Windows/Desktop/CSV\F_ALM.csv
Datos exportados de la tabla F_TAR a C:/Users/Windows/Desktop/CSV\F_TAR.csv
Datos exportados de la tabla F_FAM a C:/Users/Windows/Desktop/CSV\F_FAM.csv
Datos exportados de la tabla F_SEC a C:/Users/Windows/Desktop/CSV\F_SEC.csv

2024-08-07 11:32:07,454 - INFO - STDERR: c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

2024-08-07 11:32:07,458 - INFO - Exportación a CSV completada con éxito.
2024-08-07 11:32:07,460 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\conversor_json.py C:/Users/Windows/Desktop/CSV\F_ART.csv C:/Users/Windows/Desktop/CSV\F_LTA.csv C:/Users/Windows/Desktop/CSV\F_STO.csv
2024-08-07 11:40:02,741 - INFO - Configuración cargada desde c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\config.txt.
2024-08-07 11:40:06,418 - INFO - Ruta de la base de datos seleccionada: C:/Users/Windows/Desktop/CSV/9992024.accdb
2024-08-07 11:40:08,824 - INFO - Carpeta de salida CSV seleccionada: C:/Users/Windows/Desktop/CSV
2024-08-07 11:40:11,519 - INFO - Iniciando sincronización manual...
2024-08-07 11:40:11,520 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py C:/Users/Windows/Desktop/CSV/9992024.accdb C:/Users/Windows/Desktop/CSV
2024-08-07 11:40:14,532 - INFO - STDOUT: Datos exportados de la tabla F_ART a C:/Users/Windows/Desktop/CSV\F_ART.csv
Datos exportados de la tabla F_ARC a C:/Users/Windows/Desktop/CSV\F_ARC.csv
Datos exportados de la tabla F_STO a C:/Users/Windows/Desktop/CSV\F_STO.csv
Datos exportados de la tabla F_STC a C:/Users/Windows/Desktop/CSV\F_STC.csv
Datos exportados de la tabla F_LTA a C:/Users/Windows/Desktop/CSV\F_LTA.csv
Datos exportados de la tabla F_LTC a C:/Users/Windows/Desktop/CSV\F_LTC.csv
Datos exportados de la tabla F_ALM a C:/Users/Windows/Desktop/CSV\F_ALM.csv
Datos exportados de la tabla F_TAR a C:/Users/Windows/Desktop/CSV\F_TAR.csv
Datos exportados de la tabla F_FAM a C:/Users/Windows/Desktop/CSV\F_FAM.csv
Datos exportados de la tabla F_SEC a C:/Users/Windows/Desktop/CSV\F_SEC.csv

2024-08-07 11:40:14,534 - INFO - STDERR: c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

2024-08-07 11:40:14,538 - INFO - Exportación a CSV completada con éxito.
2024-08-07 11:40:14,540 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\conversor_json.py C:/Users/Windows/Desktop/CSV\F_ART.csv C:/Users/Windows/Desktop/CSV\F_LTA.csv C:/Users/Windows/Desktop/CSV\F_STO.csv
2024-08-07 11:49:37,236 - INFO - Configuración cargada desde c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\config.txt.
2024-08-07 11:49:40,496 - INFO - Ruta de la base de datos seleccionada: C:/Users/Windows/Desktop/CSV/9992024.accdb
2024-08-07 11:49:42,918 - INFO - Carpeta de salida CSV seleccionada: C:/Users/Windows/Desktop/CSV
2024-08-07 11:49:43,896 - INFO - Iniciando sincronización manual...
2024-08-07 11:49:43,897 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py C:/Users/Windows/Desktop/CSV/9992024.accdb C:/Users/Windows/Desktop/CSV
2024-08-07 11:49:46,911 - INFO - STDOUT: Datos exportados de la tabla F_ART a C:/Users/Windows/Desktop/CSV\F_ART.csv
Datos exportados de la tabla F_ARC a C:/Users/Windows/Desktop/CSV\F_ARC.csv
Datos exportados de la tabla F_STO a C:/Users/Windows/Desktop/CSV\F_STO.csv
Datos exportados de la tabla F_STC a C:/Users/Windows/Desktop/CSV\F_STC.csv
Datos exportados de la tabla F_LTA a C:/Users/Windows/Desktop/CSV\F_LTA.csv
Datos exportados de la tabla F_LTC a C:/Users/Windows/Desktop/CSV\F_LTC.csv
Datos exportados de la tabla F_ALM a C:/Users/Windows/Desktop/CSV\F_ALM.csv
Datos exportados de la tabla F_TAR a C:/Users/Windows/Desktop/CSV\F_TAR.csv
Datos exportados de la tabla F_FAM a C:/Users/Windows/Desktop/CSV\F_FAM.csv
Datos exportados de la tabla F_SEC a C:/Users/Windows/Desktop/CSV\F_SEC.csv

2024-08-07 11:49:46,914 - INFO - STDERR: c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

2024-08-07 11:49:46,917 - INFO - Exportación a CSV completada con éxito.
2024-08-07 11:49:46,920 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\conversor_json.py C:/Users/Windows/Desktop/CSV\F_ART.csv C:/Users/Windows/Desktop/CSV\F_LTA.csv C:/Users/Windows/Desktop/CSV\F_STO.csv
2024-08-07 11:49:57,022 - INFO - Sincronización manual cancelada.
2024-08-07 11:49:57,934 - INFO - Conversión a JSON cancelada.
2024-08-07 12:04:11,178 - INFO - Configuración cargada desde c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\config.txt.
2024-08-07 12:04:13,934 - INFO - Ruta de la base de datos seleccionada: C:/Users/Windows/Desktop/CSV/9992024.accdb
2024-08-07 12:04:17,777 - INFO - Carpeta de salida CSV seleccionada: C:/Users/Windows/Desktop/CSV
2024-08-07 12:04:18,777 - INFO - Iniciando sincronización manual...
2024-08-07 12:04:18,778 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py C:/Users/Windows/Desktop/CSV/9992024.accdb C:/Users/Windows/Desktop/CSV
2024-08-07 12:04:21,790 - INFO - STDOUT: Datos exportados de la tabla F_ART a C:/Users/Windows/Desktop/CSV\F_ART.csv
Datos exportados de la tabla F_ARC a C:/Users/Windows/Desktop/CSV\F_ARC.csv
Datos exportados de la tabla F_STO a C:/Users/Windows/Desktop/CSV\F_STO.csv
Datos exportados de la tabla F_STC a C:/Users/Windows/Desktop/CSV\F_STC.csv
Error al exportar la tabla F_LTA: [Errno 13] Permission denied: 'C:/Users/Windows/Desktop/CSV\\F_LTA.csv'
Datos exportados de la tabla F_LTC a C:/Users/Windows/Desktop/CSV\F_LTC.csv
Datos exportados de la tabla F_ALM a C:/Users/Windows/Desktop/CSV\F_ALM.csv
Datos exportados de la tabla F_TAR a C:/Users/Windows/Desktop/CSV\F_TAR.csv
Datos exportados de la tabla F_FAM a C:/Users/Windows/Desktop/CSV\F_FAM.csv
Datos exportados de la tabla F_SEC a C:/Users/Windows/Desktop/CSV\F_SEC.csv

2024-08-07 12:04:21,794 - INFO - STDERR: c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

2024-08-07 12:04:21,798 - INFO - Exportación a CSV completada con éxito.
2024-08-07 12:04:21,801 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\conversor_json.py C:/Users/Windows/Desktop/CSV\F_ART.csv C:/Users/Windows/Desktop/CSV\F_LTA.csv C:/Users/Windows/Desktop/CSV\F_STO.csv
2024-08-07 12:12:48,983 - INFO - Sincronización manual cancelada.
2024-08-07 12:12:48,984 - INFO - Conversión a JSON cancelada.
2024-08-07 12:15:06,418 - INFO - Configuración cargada desde c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\config.txt.
2024-08-07 12:15:08,746 - INFO - Ruta de la base de datos seleccionada: C:/Users/Windows/Desktop/CSV/9992024.accdb
2024-08-07 12:15:11,590 - INFO - Carpeta de salida CSV seleccionada: C:/Users/Windows/Desktop/CSV
2024-08-07 12:15:12,310 - INFO - Iniciando sincronización manual...
2024-08-07 12:15:12,311 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py C:/Users/Windows/Desktop/CSV/9992024.accdb C:/Users/Windows/Desktop/CSV
2024-08-07 12:15:15,321 - INFO - STDOUT: Datos exportados de la tabla F_ART a C:/Users/Windows/Desktop/CSV\F_ART.csv
Datos exportados de la tabla F_ARC a C:/Users/Windows/Desktop/CSV\F_ARC.csv
Datos exportados de la tabla F_STO a C:/Users/Windows/Desktop/CSV\F_STO.csv
Datos exportados de la tabla F_STC a C:/Users/Windows/Desktop/CSV\F_STC.csv
Error al exportar la tabla F_LTA: [Errno 13] Permission denied: 'C:/Users/Windows/Desktop/CSV\\F_LTA.csv'
Datos exportados de la tabla F_LTC a C:/Users/Windows/Desktop/CSV\F_LTC.csv
Datos exportados de la tabla F_ALM a C:/Users/Windows/Desktop/CSV\F_ALM.csv
Datos exportados de la tabla F_TAR a C:/Users/Windows/Desktop/CSV\F_TAR.csv
Datos exportados de la tabla F_FAM a C:/Users/Windows/Desktop/CSV\F_FAM.csv
Datos exportados de la tabla F_SEC a C:/Users/Windows/Desktop/CSV\F_SEC.csv

2024-08-07 12:15:15,325 - INFO - STDERR: c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

2024-08-07 12:15:15,328 - INFO - Exportación a CSV completada con éxito.
2024-08-07 12:15:15,331 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\conversor_json.py C:/Users/Windows/Desktop/CSV\F_ART.csv C:/Users/Windows/Desktop/CSV\F_LTA.csv C:/Users/Windows/Desktop/CSV\F_STO.csv
2024-08-07 12:22:15,154 - INFO - Configuración cargada desde c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\config.txt.
2024-08-07 12:22:18,027 - INFO - Ruta de la base de datos seleccionada: C:/Users/Windows/Desktop/CSV/9992024.accdb
2024-08-07 12:22:20,480 - INFO - Carpeta de salida CSV seleccionada: C:/Users/Windows/Desktop/CSV
2024-08-07 12:22:21,083 - INFO - Iniciando sincronización manual...
2024-08-07 12:22:21,084 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py C:/Users/Windows/Desktop/CSV/9992024.accdb C:/Users/Windows/Desktop/CSV
2024-08-07 12:22:24,097 - INFO - STDOUT: Datos exportados de la tabla F_ART a C:/Users/Windows/Desktop/CSV\F_ART.csv
Datos exportados de la tabla F_ARC a C:/Users/Windows/Desktop/CSV\F_ARC.csv
Datos exportados de la tabla F_STO a C:/Users/Windows/Desktop/CSV\F_STO.csv
Datos exportados de la tabla F_STC a C:/Users/Windows/Desktop/CSV\F_STC.csv
Error al exportar la tabla F_LTA: [Errno 13] Permission denied: 'C:/Users/Windows/Desktop/CSV\\F_LTA.csv'
Datos exportados de la tabla F_LTC a C:/Users/Windows/Desktop/CSV\F_LTC.csv
Datos exportados de la tabla F_ALM a C:/Users/Windows/Desktop/CSV\F_ALM.csv
Datos exportados de la tabla F_TAR a C:/Users/Windows/Desktop/CSV\F_TAR.csv
Datos exportados de la tabla F_FAM a C:/Users/Windows/Desktop/CSV\F_FAM.csv
Datos exportados de la tabla F_SEC a C:/Users/Windows/Desktop/CSV\F_SEC.csv

2024-08-07 12:22:24,100 - INFO - STDERR: c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

2024-08-07 12:22:24,104 - INFO - Exportación a CSV completada con éxito.
2024-08-07 12:22:24,106 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\conversor_json.py C:/Users/Windows/Desktop/CSV\F_ART.csv C:/Users/Windows/Desktop/CSV\F_LTA.csv C:/Users/Windows/Desktop/CSV\F_STO.csv
2024-08-07 12:26:30,705 - INFO - Configuración cargada desde c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\config.txt.
2024-08-07 12:26:33,402 - INFO - Ruta de la base de datos seleccionada: C:/Users/Windows/Desktop/CSV/9992024.accdb
2024-08-07 12:26:35,871 - INFO - Carpeta de salida CSV seleccionada: C:/Users/Windows/Desktop/CSV
2024-08-07 12:26:36,596 - INFO - Iniciando sincronización manual...
2024-08-07 12:26:36,597 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py C:/Users/Windows/Desktop/CSV/9992024.accdb C:/Users/Windows/Desktop/CSV
2024-08-07 12:26:39,610 - INFO - STDOUT: Datos exportados de la tabla F_ART a C:/Users/Windows/Desktop/CSV\F_ART.csv
Datos exportados de la tabla F_ARC a C:/Users/Windows/Desktop/CSV\F_ARC.csv
Datos exportados de la tabla F_STO a C:/Users/Windows/Desktop/CSV\F_STO.csv
Datos exportados de la tabla F_STC a C:/Users/Windows/Desktop/CSV\F_STC.csv
Datos exportados de la tabla F_LTA a C:/Users/Windows/Desktop/CSV\F_LTA.csv
Datos exportados de la tabla F_LTC a C:/Users/Windows/Desktop/CSV\F_LTC.csv
Datos exportados de la tabla F_ALM a C:/Users/Windows/Desktop/CSV\F_ALM.csv
Datos exportados de la tabla F_TAR a C:/Users/Windows/Desktop/CSV\F_TAR.csv
Datos exportados de la tabla F_FAM a C:/Users/Windows/Desktop/CSV\F_FAM.csv
Datos exportados de la tabla F_SEC a C:/Users/Windows/Desktop/CSV\F_SEC.csv

2024-08-07 12:26:39,613 - INFO - STDERR: c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

2024-08-07 12:26:39,617 - INFO - Exportación a CSV completada con éxito.
2024-08-07 12:26:39,620 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\conversor_json.py C:/Users/Windows/Desktop/CSV\F_ART.csv C:/Users/Windows/Desktop/CSV\F_LTA.csv C:/Users/Windows/Desktop/CSV\F_STO.csv
2024-08-07 12:59:54,407 - INFO - Configuración cargada desde c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\config.txt.
2024-08-07 12:59:58,137 - INFO - Ruta de la base de datos seleccionada: C:/Users/Windows/Desktop/CSV/9992024.accdb
2024-08-07 13:00:00,714 - INFO - Carpeta de salida CSV seleccionada: C:/Users/Windows/Desktop/CSV
2024-08-07 13:00:01,905 - INFO - Iniciando sincronización manual...
2024-08-07 13:00:01,905 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py C:/Users/Windows/Desktop/CSV/9992024.accdb C:/Users/Windows/Desktop/CSV
2024-08-07 13:00:06,919 - INFO - STDOUT: Error al exportar la tabla F_ART: [Errno 13] Permission denied: 'C:/Users/Windows/Desktop/CSV\\F_ART.csv'
Datos exportados de la tabla F_ARC a C:/Users/Windows/Desktop/CSV\F_ARC.csv
Datos exportados de la tabla F_STO a C:/Users/Windows/Desktop/CSV\F_STO.csv
Datos exportados de la tabla F_STC a C:/Users/Windows/Desktop/CSV\F_STC.csv
Datos exportados de la tabla F_LTA a C:/Users/Windows/Desktop/CSV\F_LTA.csv
Datos exportados de la tabla F_LTC a C:/Users/Windows/Desktop/CSV\F_LTC.csv
Datos exportados de la tabla F_ALM a C:/Users/Windows/Desktop/CSV\F_ALM.csv
Datos exportados de la tabla F_TAR a C:/Users/Windows/Desktop/CSV\F_TAR.csv
Datos exportados de la tabla F_FAM a C:/Users/Windows/Desktop/CSV\F_FAM.csv
Datos exportados de la tabla F_SEC a C:/Users/Windows/Desktop/CSV\F_SEC.csv

2024-08-07 13:00:06,922 - INFO - STDERR: c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\export_to_csv.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

2024-08-07 13:00:06,925 - INFO - Exportación a CSV completada con éxito.
2024-08-07 13:00:06,928 - INFO - Ejecutando comando: python c:\Users\Windows\Documents\sincronizador-factusol - copia\scripts\conversor_json.py C:/Users/Windows/Desktop/CSV\F_ART.csv C:/Users/Windows/Desktop/CSV\F_LTA.csv C:/Users/Windows/Desktop/CSV\F_STO.csv
2024-08-07 13:00:45,821 - INFO - Sincronización manual cancelada.
2024-08-07 13:00:45,950 - INFO - Conversión a JSON cancelada.
